### ISSUE TITLE
Add to awesome-dpsg list

### ISSUE THREAD

**Issue by mstoetzer** [zoomyboy/scout-robot#9]
Hi, ich möchte Dein Repo gerne in die awesome-dpsg Liste aufnehmen: https://github.com/mstoetzer/awesome-dpsg

**Comment by zoomyboy** [comment]
hi,
sorry, dass ich mich jetzt erst melde.... 
Das hier ist ne sehr alte Version. Die neue findest du hier: 



Werde beizeiten mal ne anständige Doku dazu erstellen. Die Version hier gilt als stable und wird bereits von einigen Stämmen genutzt.
